"""Tutorial integration harness.

Runs every tutorial (via combined_tutorials.py, generated by bin/tutorials_to_py.py)
and compares the printouts against test_print_output_reference.txt.

Usage (run from the tests/ directory):
    python CICD_test.py                 # text-only, headless, CI-friendly (no kaleido needed)
    python CICD_test.py --show-diffs    # also print the diff to stdout
    python CICD_test.py --collage       # also render figures to PNGs + collage.png (needs kaleido + pillow)

Exit code is non-zero if differences are found, so this can gate CI. Non-deterministic
set/dict ordering in printouts is normalised before diffing so it is not a false positive.
If you change a tutorial notebook, re-run bin/tutorials_to_py.py to refresh combined_tutorials.py.
"""
import argparse
import difflib
import os
import re
import subprocess
import sys
from datetime import datetime


def run_tutorials():
    with open('combined_tutorials.py') as file:
        script = file.readlines()
    # prefix progress updates so a long run shows life on stderr
    script = ['import sys\n'] + [
        f'sys.stderr.write("Progress: {int(i / len(script) * 100)}%\\n")\n{line}' if line == '# In[ ]:\n' else line
        for i, line in enumerate(script)
    ]
    with open('temp.py', 'w') as file:
        file.write(''.join(script))
    try:
        with open('test_print_output.txt', 'w') as f:
            subprocess.run([sys.executable, 'temp.py'], stdout=f, check=True)
    finally:
        if os.path.exists('temp.py'):
            os.remove('temp.py')


def _normalize(line):
    '''Sort the contents of any {...} group so non-deterministic set/dict ordering
    (e.g. "step types {'Point', 'Extruder'}") is not reported as a difference.'''
    def sort_group(m):
        items = [item.strip() for item in m.group(1).split(',')]
        return '{' + ', '.join(sorted(items)) + '}'
    return re.sub(r'\{([^{}]*)\}', sort_group, line)


def compare_files(current, reference):
    with open(current) as f1, open(reference) as f2:
        text1 = [_normalize(line) for line in f1]
        text2 = [_normalize(line) for line in f2]
    return [line for line in difflib.ndiff(text1, text2)
            if line.startswith('- ') or line.startswith('+ ')]


def collage_all_images():
    from PIL import Image, ImageDraw
    png_files = [f for f in os.listdir('.') if f.endswith('.png') and f not in ('collage.png', 'collage_reference.png')]
    if not png_files:
        print('no figures were generated - nothing to collage')
        return
    images = [Image.open(f) for f in png_files]
    images.sort(key=lambda img: img.filename)
    width, height = 200, 125
    num_rows = int(len(images) ** 0.5)
    num_cols = (len(images) + num_rows - 1) // num_rows
    images = [img.resize((width, height)) for img in images]
    collage = Image.new('RGBA', (width * num_cols, height * num_rows))
    for i, img in enumerate(images):
        row, col = i // num_cols, i % num_cols
        collage.paste(img, (col * width, row * height))
    draw = ImageDraw.Draw(collage)
    draw.text((collage.width - 150, collage.height - 20),
              datetime.now().strftime("%Y-%m-%d %H:%M:%S"), fill=(255, 255, 255, 128))
    collage.save('collage.png')
    print('figures collated in tests/collage.png - confirm it matches collage_reference.png')


def delete_redundant_files():
    for f in os.listdir('.'):
        if f.endswith(('.png', '.gcode', '.json', '.stl')) and f not in ('collage.png', 'collage_reference.png'):
            os.remove(f)


def main():
    parser = argparse.ArgumentParser(description='Run the tutorial integration test.')
    parser.add_argument('--show-diffs', action='store_true', help='print the diff to stdout')
    parser.add_argument('--collage', action='store_true',
                        help='render figures to PNGs and build collage.png (needs kaleido + pillow)')
    args = parser.parse_args()

    # 'True' -> write figure PNGs (needs kaleido); 'headless' -> no image output, no browser
    os.environ['FULLCONTROL_CICD_TESTING'] = 'True' if args.collage else 'headless'

    print('running all tutorial notebooks - this may take a few minutes...')
    run_tutorials()
    del os.environ['FULLCONTROL_CICD_TESTING']

    diff = compare_files('test_print_output.txt', 'test_print_output_reference.txt')
    result = [datetime.now().strftime("test results generated %d-%m-%Y__%H-%M-%S\n")]
    if diff:
        result.append(f"warning: {len(diff)} differences found vs the reference printouts "
                      "(after normalising set/dict ordering). If these are expected (e.g. a tutorial "
                      "or intended behaviour changed), refresh test_print_output_reference.txt.")
        result.append(''.join(diff))
        print(result[1])
        if args.show_diffs:
            print(result[-1])
    else:
        result.append("great! no differences found between tutorial printouts and the reference.")
        print(result[-1])

    if args.collage:
        collage_all_images()
    delete_redundant_files()

    with open('test_result.txt', 'w') as file:
        file.write('\n'.join(result))
    print('test results saved to test_result.txt')
    return 1 if diff else 0


if __name__ == '__main__':
    sys.exit(main())
