"""STL export for triangle meshes (binary + ASCII), separated from mesh
generation so the geometry classes stay focused on building meshes."""
import math
import pathlib
import struct
from datetime import datetime

import numpy as np


class MeshExporter:
    def __init__(self, metadata: dict | None = None,
                 bodies: list | None = None):
        self.metadata = metadata or {} # default to empty dictionary
        self._bodies = bodies or [self]

    @property
    def triangle_points(self):
        return NotImplemented

    @property
    def mesh_normals(self):
        ''' Assumes `triangle_indices` are defined anti-clockwise. '''
        if (cached := getattr(self, '_mesh_normals', None)) is not None:
            return cached
        triangle_points = self.triangle_points
        # anticlockwise point order when viewed from outside
        first_vectors = triangle_points[1::3] - triangle_points[::3]
        second_vectors = triangle_points[2::3] - triangle_points[::3]
        self._mesh_normals = np.cross(first_vectors, second_vectors)
        return self._mesh_normals

    def to_stl(self, path: pathlib.Path | str, binary: bool = True,
               overwrite: bool = False, combined_file: bool = True):
        write_header = self._write_binary_stl_header if binary else lambda out: None
        write_data = self._write_binary_stl_data if binary else self._write_ascii_stl_data

        path = pathlib.Path(path)
        name = self.metadata.get('name', path.stem)
        num_bodies = len(self._bodies)
        # Calculate digits needed for zero-padding increments
        digits = math.ceil(math.log10(num_bodies)) + 1
        mode = 'w' + 'b'*binary
        if combined_file or num_bodies == 1:
            if num_bodies > 1:
                print("WARNING! Multi-object STL file - may not work in some softwares, nor with stl_type='binary'.")

            with self.valid_path(path, overwrite).open(mode) as out:
                write_header(out)
                for index, body in enumerate(self._bodies):
                    identifier = (
                        index if binary
                        else (name if num_bodies == 1 else f'{name}_{index:>0{digits}}')
                    )
                    write_data(out, body.mesh_normals,
                               body.triangle_points.reshape(-1,9), identifier)
        else:
            for index, body in enumerate(self._bodies):
                file_path = self.valid_path(path.with_stem(f'{path.stem}_{index:>0{digits}}'),
                                            overwrite)
                with file_path.open(mode) as out:
                    identifier = 0 if binary else name
                    write_header(out)
                    write_data(out, body.mesh_normals,
                               body.triangle_points.reshape(-1,9), identifier)

    @staticmethod
    def _write_ascii_stl_data(out, mesh_normals, triangle_points, solid_name: str = 'object'):
        print(f'solid {solid_name} # Generated by FullControlXYZ', file=out)
        for n, vs in zip(mesh_normals, triangle_points):
            print(
                f'facet normal {n[0]:e} {n[1]:e} {n[2]:e}',
                 '    outer loop',
                f'        vertex {vs[0]:e} {vs[1]:e} {vs[2]:e}',
                f'        vertex {vs[3]:e} {vs[4]:e} {vs[5]:e}',
                f'        vertex {vs[6]:e} {vs[7]:e} {vs[8]:e}',
                 '    endloop',
                 'endfacet',
                sep='\n', file=out)
        print(f'endsolid {solid_name}', file=out)

    def _write_binary_stl_header(self, out):
        UNITS = self.metadata.get('units', 'mm')
        AUTHOR = self.metadata.get('author', None)
        author = f'{AUTHOR=},' if AUTHOR is not None else ''

        header = bytearray([0]*80)
        # header is arbitrary, but put some meaningful data into it
        #  TODO: support optional COLOR and MATERIAL fields
        #    'COLOR' should be a 4-byte RGBA value, as a simple full-object color
        #    'MATERIAL' should be diffuse reflection, specular highlight, ambient light
        #      as 4-byte RGBA values - preferred over COLOR
        header_data = f'STL,{UNITS=},{author}SOFTWARE=FullControlXYZ'.encode()
        header[:len(header_data)] = header_data
        out.write(header[:80]) # ensure header is valid

    @staticmethod
    def _write_binary_stl_data(out, mesh_normals, triangle_points, solid_index: int = 0):
        num_triangles = len(triangle_points) # one triangle per data row
        if solid_index == 0:
            out.write(struct.pack('<I', num_triangles))

        attribute_byte_count = solid_index or 0 # TODO: support facet color options
        # Create a structured array in the STL binary format
        out_data = np.empty(num_triangles, dtype=[
            *((f'n{axis}', 'f4') for axis in 'xyz'),
            *((f'v{vertex}{axis}', 'f4') for vertex in '123' for axis in 'xyz'),
            ('attrib','u2')
        ])
        # Copy across the data
        for index, axis in enumerate('xyz'):
            out_data[f'n{axis}'] = mesh_normals[:, index]
            for vi, vertex in enumerate('123'):
                out_data[f'v{vertex}{axis}'] = triangle_points[:, vi*3+index]
        out_data['attrib'] = attribute_byte_count
        # Dump it to the output file
        out_data.tofile(out)
        # TODO compare timing (and memory usage?) for large meshes
        #  Numpy approach expected to be much faster than looping + struct packing
        #for n, vs in zip(mesh_normals, triangle_points):
        #    out.write(struct.pack('<'+'f'*(3*(1+3))+'H', *n, *vs, attribute_byte_count))

    @staticmethod
    def valid_path(path: pathlib.Path | str, overwrite: bool = False) -> pathlib.Path:
        path = pathlib.Path(path) # ensure a valid Path object
        # Add a timestamp if the file already exists and we don't want to overwrite it
        if not overwrite and path.is_file():
            path = path.with_stem(
                f'{path.stem}__{datetime.today().strftime("%d-%m-%Y__%H-%M-%S")}'
            )
        return path
